# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

strategy:
      matrix:
        node-version: [14.x]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 🛎️
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm --version

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm --version
          npm install
          npm run build
          bash ./create_cname.sh
          echo 'CNAME created'

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist
          clean: true
          
